import React, { useState } from 'react';
import { Search, Edit, Grid, Zap, PlusCircle } from 'lucide-react';

const Hero: React.FC = () => {
  const [query, setQuery] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (query.trim()) {
      // Handle form submission - would connect to backend in production
      alert(`Analyzing: ${query}`);
      setQuery('');
    }
  };

  return (
    <section className="pt-32 pb-16 md:pt-40 md:pb-24 bg-background relative overflow-hidden">
      <div className="container-custom">
        <div className="text-center max-w-4xl mx-auto">
          <h1 className="mb-6 text-primary font-bold">
            Uncover Every Angle. Instantly.
          </h1>
          <p className="mb-8 text-secondary text-lg md:text-xl max-w-3xl mx-auto">
            InsightBlast AI helps you explore complex questions and ideas from multiple perspectives using the power of AI.
          </p>

          <form onSubmit={handleSubmit} className="mb-16">
            <div className="flex flex-col md:flex-row gap-4 max-w-3xl mx-auto">
              <div className="relative flex-grow">
                <input
                  type="text"
                  placeholder="Enter your question or idea here..."
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  className="w-full px-6 py-4 rounded-xl border border-separator bg-card text-primary focus:outline-none focus:ring-2 focus:ring-accent/50 transition-all shadow-sm"
                />
                <span className="absolute right-4 top-1/2 transform -translate-y-1/2 text-secondary/50">
                  <Search size={20} />
                </span>
              </div>
              <button 
                type="submit" 
                className="btn btn-primary flex-shrink-0 flex items-center justify-center"
              >
                <span>Blast Off!</span>
                <Zap size={18} className="ml-2" />
              </button>
            </div>
          </form>

          <div id="how-it-works">
            <h3 className="mb-8 text-primary">How to Get Started:</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
              <div className="flex flex-col items-center">
                <div className="w-16 h-16 mb-4 flex items-center justify-center bg-accent/10 rounded-full text-accent">
                  <Edit size={24} />
                </div>
                <h4 className="font-medium text-primary mb-2">1. Input Your Query</h4>
                <p className="text-secondary text-sm text-center">Type your question, idea, or topic into the search field.</p>
              </div>
              
              <div className="flex flex-col items-center">
                <div className="w-16 h-16 mb-4 flex items-center justify-center bg-accent/10 rounded-full text-accent">
                  <Grid size={24} />
                </div>
                <h4 className="font-medium text-primary mb-2">2. See Analysis Angles</h4>
                <p className="text-secondary text-sm text-center">View multiple perspectives generated by our AI.</p>
              </div>
              
              <div className="flex flex-col items-center">
                <div className="w-16 h-16 mb-4 flex items-center justify-center bg-accent/10 rounded-full text-accent">
                  <Search size={24} />
                </div>
                <h4 className="font-medium text-primary mb-2">3. Click to Explore</h4>
                <p className="text-secondary text-sm text-center">Dive into any angle for detailed insights and analysis.</p>
              </div>
              
              <div className="flex flex-col items-center">
                <div className="w-16 h-16 mb-4 flex items-center justify-center bg-accent/10 rounded-full text-accent">
                  <PlusCircle size={24} />
                </div>
                <h4 className="font-medium text-primary mb-2">4. Dive Deeper & Re-Blast</h4>
                <p className="text-secondary text-sm text-center">Refine your understanding or explore new directions.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      {/* Decorative background elements */}
      <div className="absolute -top-40 -right-40 w-96 h-96 bg-accent/5 rounded-full blur-3xl"></div>
      <div className="absolute -bottom-20 -left-20 w-80 h-80 bg-accent/5 rounded-full blur-3xl"></div>
    </section>
  );
};

export default Hero;